[book]
authors = ["mtantaoui"]
language = "en"
multilingual = false
src = "src"
title = "Integrate: Numerical Integration in Rust"

[output.html]
git-repository-url = "https://github.com/mtantaoui/Integrate"
mathjax-support = true
katex = true

