[book]
authors = ["mtantaoui"]
language = "en"
src = "src"
title = "Integrate: Numerical Integration in Rust"

[output.html]
git-repository-url = "https://github.com/mtantaoui/Integrate"
mathjax-support = true

[output.html.playground]
runnable = false
