name: Rust CI and Documentation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Since you can't use actions/checkout, you'll need an internal version or use git commands directly
      - name: Checkout code
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch
          git checkout -f ${{ github.sha }}

      # Install Rust
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup default stable
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Run tests
      - name: Run tests
        run: |
          cargo build --verbose
          cargo test --verbose

      # Format code
      - name: Format code
        run: |
          rustup component add rustfmt
          cargo fmt --all --check

      # Install mdBook manually
      - name: Install mdBook
        run: |
          cargo install mdbook

      # Build documentation
      - name: Build mdBook
        run: |
          # Detect the mdBook directory
          if [ -d "book" ]; then
            mdbook build book
            echo "PUBLISH_DIR=./book/book" >> $GITHUB_ENV
          else
            echo "ERROR: Could not find mdBook directory"
            ls -la
            exit 1
          fi

      - name: Ensure gh-pages Branch Exists
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git reset --hard
          git clean -fd
          git commit --allow-empty -m "Initialize gh-pages branch" || true
          git push origin gh-pages || true

      # Deploy to GitHub Pages without using third-party actions
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
          publish_branch: gh-pages

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CRATE_TOKEN}
        env:
          CRATE_TOKEN: ${{ secrets.CRATE_TOKEN }}

  check:
    name: Check (1.63.0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cargo/registry/index
          key: cargo-git-index
      - uses: dtolnay/rust-toolchain@1.63.0
      - run: cargo check --verbose

  test:
    name: Test (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --verbose
      - run: cargo test --verbose

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.72.1
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  # One job that "summarizes" the success state of this pipeline. This can then be added to branch
  # protection, rather than having to add each job separately.
  success:
    name: Success
    runs-on: ubuntu-latest
    needs: [check, test, fmt]
    # Github branch protection is exceedingly silly and treats "jobs skipped because a dependency
    # failed" as success. So we have to do some contortions to ensure the job fails if any of its
    # dependencies fails.
    if: always() # make sure this is never "skipped"
    steps:
      # Manually check the status of all dependencies. `if: failure()` does not work.
      - name: check if any dependency failed
        run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
