name: Minimal mdBook

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: List directories
        run: ls -la

      - name: Check for mdBook directories
        run: |
          if [ -d "book" ]; then
            echo "Found 'book' directory"
          fi
          if [ -d "docs" ]; then
            echo "Found 'docs' directory"
          fi
          if [ -d "user_guide" ]; then
            echo "Found 'user_guide' directory"
          fi
